app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired, ValidationError

class BotForm(FlaskForm):
    name = StringField('Nome do bot', validators=[DataRequired()])
    submit   = SubmitField('Criar')

app/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__, template_folder='templates')

from app.main import routes

app/main/routes.py
from flask import render_template, redirect, url_for, flash, request
from flask_login import current_user, login_required
from app import db
from app.models import User, Bot, Message
from app.main import bp
from app.main.forms import BotForm

@bp.route('/')
@bp.route('/index')
@login_required
def index():
    bots = Bot.query.filter_by(owner_id=current_user.id)
    return render_template('index.html', bots=bots, user=current_user)

@bp.route('/makebot', methods=['POST','GET'])
@login_required
def botform():
    form = BotForm()
    if form.validate_on_submit():
        bot = Bot(name=form.name.data, owner_id=current_user.id)
        bot.setHash()
        db.session.add(bot)
        db.session.commit()
        return redirect(url_for('main.index'))
    return render_template('makebot.html', form=form)

app/main/templates/_bot.html
<style>
    table tr td:last-child {
        text-align: right;
    }
</style>
<table class="table table-hover">
    <tr>
        <td>
            <b>{{bot.name}}</b>
            <br><br>
        </td>
        <td>
        </td>
        <td class="">
            <span>
                <a href="{{url_for('chat.chat', bhash=bot.bhash)}}">
                    <button type="button" class="btn btn-success btn-lg">
                        <span>Conversar</span>
                    </button>
                </a>
            </span>
        </td>
    </tr>
</table>

app/main/templates/index.html
{% extends 'base.html' %}

{% block app_content %}
    <h1>Seus bots</h1>
    {% if bots != none%}
    {%for bot in bots%}
        {% include '_bot.html' %}
    {%endfor%}
    {%else%}
    <p>Voce nao tem nenhum bot :(<br>Quer criar um agora?</p>
    {%endif%}
    <a class="btn btn-success" href="{{url_for('main.botform')}}">Criar bot</a>
{% endblock %}

app/main/templates/makebot.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block app_content %}
    <h1>Criar bot</h1>
    <div class="row">
        <div class="col-md-4">
            {{ wtf.quick_form(form) }}
        </div>
    </div>
{% endblock %}